sifive/sifive-blocks

src/main/scala/devices/i2c/I2C.scala, src/main/scala/devices/i2c/I2CCtrlRegs.scala, src/main/scala/devices/i2c/I2CPeriphery.scala, src/main/scala/devices/i2c/I2CPins.scala
i2c master with the same interface as: https://opencores.org/project,i2c
Linux driver: http://lxr.free-electrons.com/source/drivers/i2c/busses/i2c-ocores.c?v=4.6
=> I2c implementation

src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala, src/main/scala/ip/xilinx/vc707mig/vc707mig.scala
Use _chisel3 analog for MIG inout
=> Use _chisel3 analog for MIG inout

src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala, src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1.scala, src/main/scala/ip/xilinx/vc707axi_to_pcie_x1/vc707axi_to_pcie_x1.scala
This tracks the pipelined mmio rocket changes
=> axi4: switch to new pipelined converters

src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala
This makes placement of the L2 and DDR controller easier.
=> xilinx mig: put a buffer infront of the controller

src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala, src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1.scala, src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1Periphery.scala, src/main/scala/ip/xilinx/vc707mig/vc707mig.scala
This reproduces the earlier work of @henrystyles to move PCIe into another clock domain.
=> Async PCIe

src/main/scala/devices/gpio/GPIO.scala
This makes the IOF functionality of the GPIO pins optional. The default is False, which means that existing code which uses the IOF functionality will need to set it to be true.
This reduces lots of dead code elimination runtime and the IOF control registers, which would not be constant-propagated away during synthesis otherwise.
=> gpio: Make IOF optional

src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/gpio/GPIOPeriphery.scala, src/main/scala/devices/gpio/JTAG.scala, src/main/scala/devices/i2c/I2C.scala, src/main/scala/devices/i2c/I2CPeriphery.scala, src/main/scala/devices/mockaon/MockAON.scala, src/main/scala/devices/mockaon/MockAONPeriphery.scala, src/main/scala/devices/mockaon/MockAONWrapper.scala, src/main/scala/devices/mockaon/PMU.scala, src/main/scala/devices/mockaon/WatchdogTimer.scala, src/main/scala/devices/pwm/PWM.scala, src/main/scala/devices/pwm/PWMPeriphery.scala, src/main/scala/devices/spi/SPIBundle.scala, src/main/scala/devices/spi/SPIPeriphery.scala, src/main/scala/devices/spi/TLSPI.scala, src/main/scala/devices/spi/TLSPIFlash.scala, src/main/scala/devices/uart/UART.scala, src/main/scala/devices/uart/UARTPeriphery.scala, src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala, src/main/scala/devices/xilinxvc707mig/XilinxVC707MIGPeriphery.scala, src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1.scala, src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1Periphery.scala, src/main/scala/ip/xilinx/vc707axi_to_pcie_x1/vc707axi_to_pcie_x1.scala, src/main/scala/ip/xilinx/vc707mig/vc707mig.scala, src/main/scala/util/RegMapFIFO.scala, src/main/scala/util/ResetCatchAndSync.scala, src/main/scala/util/Timer.scala
Only change imports, not functionality.
=> Refactor package hierarchy

src/main/scala/devices/uart/UART.scala, src/main/scala/devices/uart/UARTPeriphery.scala
matching PR for https://github.com/freechipsproject/rocket-chip/pull/887
=> uart: use PeripheryBusParams.frequency to calculate default divisor

src/main/scala/devices/spi/SPIFlash.scala
**Issue**: When the memory-mapped flash region is accessed while the flash read mode is disabled (`fctrl.en` flag is clear), the SPI flash controller generates an invalid response on the D channel.  This may cause the TileLink bus to deadlock.
**Workaround**: Software should avoid accessing the memory-mapped flash region when the SPI controller is not in the flash read mode.
=> spi: Fix invalid D channel response when flash interface is disabled

src/main/scala/devices/uart/UART.scala
This is the first use of PlusArg in synthesis. Hopefully nothing is too badly broken.
=> uart: make it easy to simulate large text printouts

src/main/scala/devices/spi/SPIPeriphery.scala, src/main/scala/devices/spi/TLSPIFlash.scala
This will prevent SPI from blocking other pbus requests.
=> spi: put a request buffer infront of SPI

src/main/scala/devices/uart/UART.scala
This refactors the receiver logic to compensate for the case of the baud rate divisor not being multiple of the oversampling period.
Previously, the bit time was effectively rounded to `s * floor(div / s)` cycles, where `s` is the oversampling factor - the number of intermediate samples for each data bit.  The remainder `r = div % s` was ignored, thereby resulting in gradually accumulated drift that became significant for `div` values on the same order of magnitude as `s`.
The revised approach inserts the required additional delay by extending the last `r` samples of a given data bit by one cycle each.
=> uart: Eliminate systemic baud rate error with low divisor values

src/main/scala/devices/spi/SPIPins.scala
This makes it easier to apply constraints / waivers based on the register names.
Synchronizer register names change from _T_123 to:
...spi_dq_0_sync.sync_0
...spi_dq_0_sync.sync_1
...spi_dq_0_sync.sync_2
(where the "last" synchronizer (closest to the core clock domain) is the 0th one)
=> SPI: Use the standard synchronizer primitive for the SPI DQ inputs

src/main/scala/devices/chiplink/Bundles.scala, src/main/scala/devices/chiplink/CAM.scala, src/main/scala/devices/chiplink/ChipLink.scala, src/main/scala/devices/chiplink/Parameters.scala, src/main/scala/devices/chiplink/Partial.scala, src/main/scala/devices/chiplink/RX.scala, src/main/scala/devices/chiplink/SinkA.scala, src/main/scala/devices/chiplink/SinkB.scala, src/main/scala/devices/chiplink/SinkC.scala, src/main/scala/devices/chiplink/SinkD.scala, src/main/scala/devices/chiplink/SinkE.scala, src/main/scala/devices/chiplink/SourceA.scala, src/main/scala/devices/chiplink/SourceB.scala, src/main/scala/devices/chiplink/SourceC.scala, src/main/scala/devices/chiplink/SourceD.scala, src/main/scala/devices/chiplink/SourceE.scala, src/main/scala/devices/chiplink/TX.scala, src/main/scala/devices/msi/MSIMaster.scala
This PR includes all the state machines necessary to speak the ChipLink protocol. Bindings in freedom to create an FPGA-based slave will follow in a future PR.
=> devices: add support for the chiplink protocol

src/main/scala/devices/msi/MSIMaster.scala
This should still cost nothing in the case where all the targets are aligned.
=> MSIMaster: support misaligned target addresses

src/main/scala/devices/chiplink/SourceA.scala, src/main/scala/devices/chiplink/SourceB.scala, src/main/scala/devices/chiplink/SourceC.scala, src/main/scala/devices/chiplink/SourceD.scala
This tracks changes made in rocket-chip.
=> chiplink: switch to corrupt/denied

src/main/scala/devices/chiplink/ChipLink.scala, src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/gpio/GPIOPeriphery.scala, src/main/scala/devices/gpio/GPIOPins.scala, src/main/scala/devices/i2c/I2C.scala, src/main/scala/devices/i2c/I2CPeriphery.scala, src/main/scala/devices/mockaon/MockAONPeriphery.scala, src/main/scala/devices/pwm/PWM.scala, src/main/scala/devices/pwm/PWMPeriphery.scala, src/main/scala/devices/pwm/PWMPins.scala, src/main/scala/devices/spi/SPIPeriphery.scala, src/main/scala/devices/spi/TLSPI.scala, src/main/scala/devices/spi/TLSPIFlash.scala, src/main/scala/devices/uart/UART.scala, src/main/scala/devices/uart/UARTPeriphery.scala
Adds support for clock crossings with IO peripherals
=> Add HasCrossing to IO peripherals

src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/spi/TLSPI.scala
This PR requires https://github.com/freechipsproject/rocket-chip
=> Add DTS fields needed by linux kernel drivers

src/main/scala/devices/spi/TLSPI.scala
This depends on https://github.com/freechipsproject/rocket-chip/pull/1533
=> spi: DTS descriptions for flash + MMC SPI devices

src/main/scala/devices/chiplink/ChipLink.scala, src/main/scala/devices/chiplink/Parameters.scala, src/main/scala/devices/chiplink/RX.scala, src/main/scala/devices/chiplink/TX.scala, src/main/scala/devices/mockaon/MockAONWrapper.scala
This just matches the argument changes.
=> chiplink: update to newer rocket-chip async crossing api

src/main/scala/devices/chiplink/ChipLink.scala, src/main/scala/devices/chiplink/Parameters.scala, src/main/scala/devices/chiplink/SourceA.scala, src/main/scala/devices/chiplink/SourceC.scala
When the link is down, intercept Probes and respond with NtoN.
=> Chiplink probe bypass

src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/gpio/GPIOCtrlRegs.scala
add pass-through active-high/low interrupt enable control registers and compatibility string
=> FU-1204 pass-through active-high/low interrupt enable

src/main/scala/devices/stream/PseudoStream.scala
I was having a little bit of difficulty reading the code in https://github.com/sifive/sifive-blocks/pull/105, so here's a suggestion improving the readability of that code. I split up arguments with newlines and putting closing parentheses on their own line, which I think makes it a bit easier to distinguish the arguments than to put some arguments on the same line while others on separate lines. I also got rid of the parentheses around the list elements, which I thought made it more difficult to read because of the excessive closing parentheses.
This PR targets https://github.com/sifive/sifive-blocks/pull/105, so if you like these changes, feel free to merge this into that.
=> Stream device: Clean up linebreaks and parentheses for readability.

src/main/scala/devices/chiplink/ChipLink.scala, src/main/scala/devices/chiplink/StuckSnooper.scala
Improve performance of coherent traffic through ChipLink master bypass path
=> ChipLink StuckSnooper

src/main/scala/devices/mockaon/MockAONPeriphery.scala
Goes with https://github.com/chipsalliance/rocket-chip/pull/2155
=> Debug: Make Debug Module optional

build.wake, ivydependencies.json, wit-manifest.json
wake files for v0.15. update wit files for renamed repos
=> update wit and wake files

src/main/scala/devices/mockaon/MockAON.scala, src/main/scala/devices/mockaon/RTC.scala, src/main/scala/devices/mockaon/WatchdogTimer.scala, src/main/scala/devices/pwm/PWM.scala
I would like to merge @jackkoenig's changes
=> Fix imports for Chisel 3.2

src/main/scala/devices/chiplink/CAM.scala
This is necessary to get a Reset-typed reset.
=> chiplink: upgrade CAM to chisel3

src/main/scala/devices/spi/TLSPIFlash.scala
Before this change, the register map would show up twice in the object model for both memory regions of the SPIFLash. Now it only shows up in control region, as is appropriate.
=> TLSPIFlash: correct OM register map generation code

build.wake
also, add package root location variable
=> wake: publish ivydependencies.json location

.github/workflows/test.yml, wit-manifest.json
This runs the scala compile via the wake build system.
=> Add GitHub actions

src/main/scala/util/DFT.scala
Add 2 Traits for DFT
Trait HasDFT:
dftNode = Source Node for DFT
makePort = Make Port for DFT
Trait CanHaveDFT:
dftNode = collect LazyModules with SourceNode for DFT
call the dftNode.foreach(_.maketPort)
=> Add HasDFT, CanHaveDFT Trait

src/main/scala/devices/spi/SPIBundle.scala, src/main/scala/devices/spi/SPIPhysical.scala
Add ie Port in SPI Physical layer
Simply ie port is assigned ~oe
=> SPI ie Port

src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/gpio/GPIOCtrlRegs.scala, src/main/scala/devices/pinctrl/PinCtrl.scala
Connect additional GPIO pins with more control registers.
=> add additional GPIO pin connections

src/main/scala/devices/gpio/GPIO.scala, src/main/scala/devices/gpio/GPIOPeriphery.scala, src/main/scala/devices/gpio/IOF.scala
This PR is for making connection of GPIO function pin in the design, not shell.
Currently, GPIO pin and function pin are in a bundle, so, we must connect to function in the shell level.
But, I think this connection should be made at the design top level.
=> GPIO: split function I/O bundle from GPIO bundle

src/main/scala/devices/gpio/IOF.scala
This fixes the problem that the input pin is not connected.
=> fix incorrect connection for input pin
