sifive/sifive-blocks

- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/spi/TLSPI.scala
Previously we had to do weird things to make non-homogenous
lists of items (e.g. PWM Peripherals where ncmp were different from one to
the other) into a vector. But now Chisel supports a Record type,
and we use the HeterogeneousBag utility to do this more naturally.
This also deletes all the cruft which was introduced to get
around the limitation which doesn't exist anymore.
> Use HeterogenousBag to handle lists of peripherals

- src/main/scala/devices/mockaon/MockAONPeriphery.scala
- src/main/scala/devices/mockaon/MockAONWrapper.scala
This allows the Debug Module to perform a system reset.
TODO: Need to add isolation as well, but need to think about any combinational loops potentially introduced
> MockAON: Accept the non-debug interrupt as an input to overall reset.

- src/main/scala/devices/spi/SPIFIFO.scala
- src/main/scala/devices/spi/SPIPhysical.scala
This fixes the following issues in the SPI master peripheral.
---
* **Issue**: The output enable signal for DQ[3] is not driven properly.
* **Symptoms**: Output data from master to slave is not properly transmitted in quad mode.  Data received from the slave is unaffected.
* **Workaround**: When interfacing with SPI flash devices, do not use the "Quad Input/Output Fast Read" command (opcode `0xEB`) while in the Extended SPI protocol.  Do not use the Native Quad SPI protocol.
---
* **Issue**: Configuring the frame length to certain values causes incorrect operation.
* **Symptoms**: Certain frame lengths result in the master sending one extra clock pulse.  The slave device may then become desynchronized.
* **Workaround**: The following frame lengths are supported and can be used. Do not use …
> SPI errata fixes

- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
Some peripherals take a list of parameters, to allow for 0 or more. GPIO and SPIFlash were exceptions. I don't see a really great reason for this constraint. Alternatively, they could be Options. Thoughts?
> Make more peripherals "listable" to allow for 0 or more

- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/mockaon/MockAONPeriphery.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- src/main/scala/devices/xilinxvc707mig/XilinxVC707MIGPeriphery.scala
- src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1Periphery.scala
...to work with system-level multi-io module.
The abstract bundle traits can either be mixed into Bundles and made concrete with calls to `cloneType`, or mixed into ModuleImps and made concrete with `IO(...)`s. Examples of the latter use case are provided for each peripheral.
TODO in future PR: add more helper functions in the style of `toGPIOPins`
> periphery: convert bundle traits 

- src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala
- src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1.scala
1 - Print AXI-ID mappings
2 - Use half as many Deinterleaver buffers for the L2 backside
3 - Limit the Q depth on the PCIe control port to 2 (was 1584!)
> vc707 axi enhancements

- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/mockaon/MockAONPeriphery.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UART.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- src/main/scala/devices/xilinxvc707mig/XilinxVC707MIG.scala
- src/main/scala/devices/xilinxvc707mig/XilinxVC707MIGPeriphery.scala
- src/main/scala/devices/xilinxvc707pciex1/XilinxVC707PCIeX1Periphery.scala
Peripheral devices are now mixed-in to the `Coreplex` module where they attach to `pbus` and `ibus` using the attachment points provided by `TLBusWrapper`
> periphery: peripherals now in coreplex

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/gpio/GPIOPins.scala
- src/main/scala/devices/gpio/JTAG.scala
- src/main/scala/devices/i2c/I2C.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/i2c/I2CPins.scala
- src/main/scala/devices/jtag/JTAGPins.scala
- src/main/scala/devices/mockaon/MockAONWrapper.scala
- src/main/scala/devices/pinctrl/PinCtrl.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/spi/SPIPins.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
This also standardizes some pluralization. Bundle names (e.g. spi) is not pluralized. Inside the modules, the peripherals themselves are pluralized. This also helps avoid name conflicts.
> Seperate GPIO Peripheral Functionality

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
Makes it easier to supply bundle params from different sources without worrying about trait mix-in order.
Also clean up the calculation of UART divinit
> Allow bundle content params to be specified via a def

- src/main/scala/devices/mockaon/MockAONPeriphery.scala
This commit adds the logic to detect the external rtc toggles which was previously present in rocket-chip
> mockaon: Adds logic to detect external rtc toggles

- src/main/scala/devices/gpio/GPIOPins.scala
- src/main/scala/devices/i2c/I2CPins.scala
- src/main/scala/devices/jtag/JTAGPins.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/pwm/PWMPins.scala
- src/main/scala/devices/spi/SPIPins.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- src/main/scala/devices/uart/UARTPins.scala
In order to make more interesting named bundles similar to Pins, create super class "Signal" bundles of type T. The old XYZPins are now XYZSignals[T <: Pin]. 
All the old `fromPort` methods have to be replaced with objects on the typed bundles to increase their usability.
> Create Signal Bundles vs just Pins

- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/util/Timer.scala
If not using the on GPIO pinmux, still need an inversion capability
I used some reserved bits ~~(4-7)~~ (20-23) in the CFG register. I made them reset to 0 to maintain backwards SW compatibility (otherwise user would have to ensure that they were set to 0).
> PWM: Add the ability to invert the output directly in PWM

- src/main/scala/devices/mockaon/PMU.scala
This fixes a no implicit clock error for those Registers.
> PMU: adapt to new chisel API

- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/mockaon/MockAONPeriphery.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/pwm/PWMPins.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- src/main/scala/devices/uart/UARTPins.scala
Keep up to date with api changes in rocket-chip.
Future work will add per-peripheral clock crossing options.
> periphery: bus api update

- src/main/scala/devices/mockaon/RTC.scala
- src/main/scala/devices/mockaon/WatchdogTimer.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/util/SlaveRegIF.scala
- src/main/scala/util/Timer.scala
I wanted to add descriptions to the timer subclasses, which required changing the way they are coded somewhat in order to be able to accurately describe the subfields. I don't *think* I changed any functionality when accessing them as 32 bit registers, but it does now allow you to say, clear the IP bit with a `sb` operation.
> Add descriptions to Timers and friends

- src/main/scala/util/Timer.scala
No other timer registers have camel casing in their descriptions, remove the Lo/Hi capitalization for consistency
> Timer: countlo/counthi remove camel casing

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/chiplink/SinkD.scala
- src/main/scala/devices/chiplink/SourceD.scala
Fortunately, D-channel only uses 2 bits out of the param field.
Therefore, it is backwards compatible to re-purpose this bit.
Existing hardware will ignore it, truncating the param field.
Existing hardware will never generate it, filling it with zero.
> chiplink: support 'denied' in D-channel

- src/main/scala/devices/chiplink/ChipLink.scala
This also makes the RX/TX module<>IO symmetric.
> ChipLink: make the intentd of c2b_{clk,rst} more clear

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/gpio/GPIOPins.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/pwm/PWMPins.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
Change peripherals with pclk (tl_clk / 4), since tl_clk runs at 0-750MHz, too fast for more peripherals
> [FU-908] Drive peripherals with newly added pclk

- src/main/scala/devices/uart/UART.scala
Add an alias to allow the SiFive UART to be used as a console.
> UART: add DTS alias for console

- src/main/scala/devices/uart/UART.scala
Otherwise, linux will not use the console correctly.
> UART: use an alias, not a reference

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/chiplink/Parameters.scala
Unfortunately, the RX reset cannot be flopped the same way on both
FPGA and ASIC targets. We require the internal reset high even in the
absence of a valid RX clock. To achieve this, we need an asynchronous
reset register. On an ASIC, the obvious approach is to use the off-chip
reset as an asynchronous set that is analyzed by clock recovery.
However, on an FPGA, for performance, it is necessary to register the
off-chip signal into a register located in the IO buffer. Unfortunately,
these buffers can only take off-chip signals to D, never async set.
On an FPGA, though, it is possible to generate a reset that is high
on power-on.
> chiplink: make RX reset strategy configurable

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/chiplink/Parameters.scala
Using a function with no access outside the Module didn't work.
> chiplink: plumb fpga_reset out of the module

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/gpio/IOF.scala
- src/main/scala/devices/i2c/I2C.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/pwm/PWMPins.scala
- src/main/scala/devices/spi/SPI.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/spi/TLSPI.scala
- src/main/scala/devices/spi/TLSPIFlash.scala
- src/main/scala/devices/uart/UART.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- src/main/scala/devices/uart/UARTRx.scala
- src/main/scala/devices/uart/UARTTx.scala
The new `RegisterRouter` API has several advantages over the previously available `TLRegisterRouter` for IO devices:
- It does not require separate Bundle and ModuleImp traits for the controller implementation
- Its IO ports can be bridged to higher in the module hierarchy
- Its control register map can be clock crossed relative to the buses it is attached to
The above make it straightforward to capture the attachment of the controller to the buses in a helper object application, rather than in traits. This PR converts the GPIO, UART, PWM, I2C, SPI, and QSPI controllers, while reimplementing the behavior of the legacy traits used to attach them to `BaseSubsystems` to use `attach`.
> Refactor some peripheral devices to use RegisterRouterIO

- src/main/scala/devices/chiplink/ChipLink.scala
Its port can now be bridged without relying on the deprecated `BundleBridge` wrapper.
> chiplink: has an ioNode to create its port signal

- src/main/scala/devices/chiplink/TX.scala
This removes the credit calculation from the loops that feed the IO pads.
> chiplink: retime credit update loops to increase FPGA clock rate

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/i2c/I2C.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPI.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UART.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
- Instead of being named based on chisel valNames, devices get a standardized name and share a global index
- legacy periphery traits use async interrupt crossings
> device attachment cleanups

- src/main/scala/util/Timer.scala
Otherwise, the real bundle never gets written
> Timer: correct the initialization for maxcmp vs ncmp signals

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/chiplink/Parameters.scala
- src/main/scala/devices/chiplink/SourceA.scala
- src/main/scala/devices/chiplink/SourceC.scala
Enable chiplink to route messages to multiple error devices if each is providing a capability to respond to a different type of request.
> chiplink: find error devices per opcode

- src/main/scala/devices/mockaon/MockAONPeriphery.scala
- Moved sbus.control_bus to subsystem level
- Renamed it to cbus
- Depend less on the tilelink.CanAttachTLSlaves API
> subsystem: sbus.control_bus => cbus

- src/main/scala/devices/jtag/JTAGPins.scala
In order to use the auto `cloneType`, I had to add these `val`s.
> JTAG: Make Pins clonable

- src/main/scala/devices/spi/TLSPI.scala
- src/main/scala/devices/spi/TLSPIFlash.scala
- src/main/scala/util/RegMapFIFO.scala
Additional changes on top of #102 , this also adds some descriptions to the FIFO register fields used (currently) by SPI and UART.
As I was making this change, I realized that we need to be careful about assuming/hard-coding the SPI reg field widths, so that needs to be resolved before merging this change. I think the right thing to do is add `require`s on the current widths, dynamically add padding if necessary, or revert the change which merged these into one `RegFieldGroup`... they can all be in the same group even if they are different byte offsets, as in, they can be annotated with the same `RegFieldGroup` with different calls to `RegFieldGroup`. Will try that out shortly.
> [WIP] SPI/UART RegField Desc Cleanup

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/i2c/I2C.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/spi/SPI.scala
- src/main/scala/devices/stream/PseudoStream.scala
- src/main/scala/devices/uart/UART.scala
- src/main/scala/util/BusBlocker.scala
The QSPI case is a bit awkward because we need one blocker for each node type; for now I just make their addresses contiguous.
> Allow optional bus blockers to be inserted while attaching devices

- src/main/scala/devices/chiplink/Parameters.scala
- src/main/scala/devices/stream/PseudoStream.scala
I made the stream device register descriptions a little more organized by putting them into groups and adding the channel number to the register names to avoid multiple registers in the same device with the same name.
There should be no functional changes. 
The change also fixed some inconsistent indentation which is why it looks bigger than it is.
> Stream: Clean up register descriptions and groupings

- src/main/scala/devices/uart/UART.scala
The rxen register in the UART had "txen" erroneously set as its field name in the RegFieldDesc constructor.
This resulted in the incorrectly-named rxen register showing up as txen, and thus replacing the correct txen field in the JSON output from the Rocket/Chisel flow.
> Correct name of rxen field

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/gpio/OMGPIO.scala
Replaces https://github.com/sifive/sifive-blocks/pull/112.
This adds an Object Model for the GPIO device. Rather than changing the return values of each of the `attach*` methods for the peripherals, this PR takes the opposite approach of passing in the parent LogicalTreeNode into the attach method via the `GPIOAttachParams`, allowing the attach method to actually attach the `LogicalTreeNode`s together, much like how it attaches the various Diplomatic nodes.
> Add GPIO object model

- src/main/scala/devices/gpio/GPIO.scala
Make it easier to tie-off the GPIO inputs in designs / test harnesses.
Also add a require statement to prevent array out-of-bounds errors
> GPIO: Add a  Tie-Off Method which includes IOF pins

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/msi/MSIMaster.scala
- src/main/scala/devices/spi/TLSPIFlash.scala
fix these Chisel compile warnings:
```
method apply in object TLClientParameters is deprecated: Use TLMasterParameters.v1 instead of TLClientParameters
method apply in object TLClientPortParameters is deprecated: Use TLMasterPortParameters.v1 instead of TLClientPortParameters
method apply in object TLManagerParameters is deprecated: Use TLSlaveParameters.v1 instead of TLManagerParameters
method apply in object TLManagerPortParameters is deprecated: Use TLSlavePortParameters.v1 instead of TLManagerPortParameters
```
- Paying Off Technical Debt
> Chisel compile warning: TileLink Parameters v1

- src/main/scala/util/Devices.scala
Nothing seems to depend on this type bound.
> Devices: allow attachTo API for non-register-router devices

- src/main/scala/devices/mockaon/MockAONPeriphery.scala
fix this Chisel compile warning:
```
[warn] /federation/sifive-blocks/src/main/scala/devices/mockaon/MockAONPeriphery.scala:22:20: method apply in object IntSyncCrossingSink is deprecated (since rocket-chip 1.2): IntSyncCrossingSink which used the `sync` parameter to determine crossing type is deprecated. Use IntSyncAsyncCrossingSink, IntSyncRationalCrossingSink, or IntSyncSyncCrossingSink instead for > 1, 1, and 0 sync values respectively
[warn]   ibus.fromSync := IntSyncCrossingSink() := aon.intnode
[warn]                    ^
```
- Paying Off Technical Debt
> Chisel compile warning: deprecated IntSyncCrossingSink

- src/main/scala/util/Timer.scala
This broke tests in a larger repository.
This changed came in PR #141, but do not seem necessary.
> Timer: revert maxcmp change from 8 back to 4

- src/main/scala/devices/gpio/GPIOPeriphery.scala
- src/main/scala/devices/i2c/I2CPeriphery.scala
- src/main/scala/devices/pwm/PWMPeriphery.scala
- src/main/scala/devices/spi/SPIPeriphery.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
We would like to use the `HasPeripheryX` traits more like `CanHavePeripheryX`. Setting the `PeripheryXKey` defaults to `Nil` lets us do this without adding a `WithNoX` mixin to all our configurations.
> Set PeripheryKey defaults to Nil

- src/main/scala/devices/gpio/GPIO.scala
- src/main/scala/devices/i2c/I2C.scala
- src/main/scala/devices/pwm/PWM.scala
- src/main/scala/devices/spi/SPI.scala
- src/main/scala/devices/stream/PseudoStream.scala
- src/main/scala/devices/timer/Timer.scala
- src/main/scala/devices/uart/UART.scala
- src/main/scala/devices/wdt/TLWDT.scala
- src/main/scala/util/Devices.scala
- src/main/scala/util/Hierarchy.scala
Adds Hierarchy.scala, which introduces `CanHaveConfigurableHierarchy` and `DevicesSubsystem`, a system populated only by a `TLNetworkTopologyLocated` and whichever devices are specified in `DevicesLocated`
> Support for configurable hierarchies

- src/main/scala/devices/uart/UART.scala
- src/main/scala/devices/uart/UARTPeriphery.scala
In FireSim, we want the nominal PeripheryBus frequency to be 3.2 GHz. But this makes printing through the UART really slow, since the baud rate is hard-coded to 115200. This commit makes the baud rate configurable.
> Allow UART baudrate to be configured

- src/main/scala/devices/chiplink/ChipLink.scala
- src/main/scala/devices/chiplink/SourceB.scala
fix these Chisel warnings:
```
[warn] /federation/sifive-blocks/src/main/scala/devices/chiplink/ChipLink.scala:141:45: method supportsProbe in class TLMasterParameters is deprecated: Use supports.probe instead of supportsProbe
[warn]     require (edgeIn.client.clients.filter(_.supportsProbe).size <= 1,
[warn]                                             ^
[warn] /federation/sifive-blocks/src/main/scala/devices/chiplink/ChipLink.scala:142:88: method supportsProbe in class TLMasterParameters is deprecated: Use supports.probe instead of supportsProbe
[warn]       s"ChipLink supports at most one caching master, ${edgeIn.client.clients.filter(_.supportsProbe).map(_.name)}")
[warn]                                                                                        ^
[warn] …
```
> TileLink Diplomacy parameters supportsProbe -> supports.probe
